### ISSUE TITLE
Failure to build on CentOS6 GCC 4.4.7

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [RcppCore/RcppArmadillo#85]
When compiled on a CentOS6 (GCC 4.4.7) platform, RcppArmadillo 0.6.700.3.0 
has similar bug to one fixed in 0.4.550.2.0

I just came to install

RcppArmadillo 0.6.700.3.0

on a CentOS 6 system (GCC 4.4.7) and it failed to compile.

When I went looking for the error, I found this at stackoverflow from 2014

[RcppArmadillo: failing to install on CentOS](http://stackoverflow.com/questions/27296522/rcpparmadillo-failing-to-install-on-centos/27297411)

in which Dirk said that a similar bug had been fixed, in 0.4.550.2.0,
available from this GitHub repo.

Sadly, and somewhat strangely, this GitHub repo doesn't have
any releases (perhaps because "releases" are moved across to
the CRAN ?) however, the version above was not seemingly
propagated over to the CRAN repos, so it was confusing for
a short while.

I did think to try 0.4.550.1.0 but I guess 0.4.550.2.0 was needed
because it fixed the bug in the 1-before-it (pun intended) becuase 
that failed to compile as well.

I did manage to follow the other advice from the stackoverflow
question, which was to use 0.4.500.0, which is in the CRAN archive
for RcppArmadillo.

I attach the compilation errors from 0.6.700.3.0 in case they are of any use.
[20160415-RcppArmadillo.txt](https://github.com/RcppCore/RcppArmadillo/files/220241/20160415-RcppArmadillo.txt)

**Comment by eddelbuettel** [comment]
1. We have faithfully made release just about every month or so for several years now and you can [get them all here](https://cloud.r-project.org/src/contrib/Archive/RcppArmadillo/). I presume you know where to find the current version.

2. g++ 4.4.7 is [over four years old](https://gcc.gnu.org/gcc-4.4/).  Who are you kidding here?  Why do you bother with current RcppArmadillo?   Pick an RcppArmadillo release _from several years ago_ such as the 0.3.* series.

3. Seriously. For recent software use recent tools.

**Comment by vuw-ecs-kevin** [comment]
Just in case anyone who finds this might be confused by those answers, I just 
thought to re-iterate the bits I reported that are at odds with those answers.

> 1. We have faithfully made releases just about every month or so for
> several years now and you can get them all here.

If Release 0.4.550.2.0 is one of "them all", I couldn't find it, so apologies.

> 2. ... Pick an RcppArmadillo release from several years ago such as the 0.3.* series.

There's no need to go back to the 0.3 series: as stated, Release 0.4.500.0 is OK.

**Comment by eddelbuettel** [comment]
Here is the [ChangeLog entry you appear to have missed](https://github.com/RcppCore/RcppArmadillo/blob/master/ChangeLog#L366-L375).  I trust you can identify the sha1 of the commit yourself, should you need it.

And to reiterate: there was never a bug report here to start with as there is really as much of a point in compiling the current 0.6.700.3.0 under g++ 4.4.7 as there may be in trying to cross the continent in a horse and buggy.  It may be feasible if you are truly committed, have patience and willing to fix things along the way -- but most of us will opt for a more modern form of transportation.   

And please don't misunderstand me: I have nothing against someone using CentOS.  People are free to make their own lives as difficult as they chose.  But I just ask that they be consistent:  If "stability" is so paramount, then you really should not run a current release.  So if 0.4.500.0 does it for you, fine.   

And we all move on.

**Comment by thirdwing** [comment]
@vuw-ecs-kevin You can find all the previous release from https://cran.r-project.org/src/contrib/Archive/RcppArmadillo/

However, using a new compiler will make everyone's life easier.
